import React from 'react';
import Head from 'next/head';
import { getPostsSlugs, getPost } from '../../utils/data';
import Image from 'next/image';
import ReactMarkdown from 'react-markdown';

export const getStaticPaths = async () => {

   const slugsRes = await getPostsSlugs();
	const slugs = slugsRes.posts;

   return {
      paths: slugs.map(slug => ({params: {slug: slug.slug}})),
      fallback: false
   }

}

export const getStaticProps = async ({ params }) => {
   const postRes = await getPost(params.slug);
   const post = postRes.post;

   return {
      props: {
         post
      }
   }
}

const Post = ({ post }) => {
   console.log(post);
   return (
      <>
         <Head>
            <title>{post.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div>
            <h1>{post?.title}</h1>
            <p>{new Date(post.date).toDateString()}</p>
				<p>{post.description}</p>
            <div>
               <p>{post.author.name}</p>
               <Image 
                  src={post.author.image.url}
                  width={post.author.image.width / 3}
                  height={post.author.image.height / 3}
               />
            </div>
            <div>
               {
                  post.tags.map(tag => (
                     <span key={tag}>{tag}</span>
                  ))
               }
				</div>
            <section className='prose'>
               <ReactMarkdown
                  escapeHtml={false}
               >
                  {post.content.markdown}
               </ReactMarkdown>
            </section>
         </div>
      </>
   )
}

export default Post
