import Head from 'next/head';
import Link from 'next/link';
import { getPortfolioSlugs, getPortfolioItem } from '../../utils/data';
import { useRouter } from 'next/router';

export const getStaticPaths = async () => {

   const slugs = await getPortfolioSlugs();
   console.log(slugs);

   return {
      paths: [],
      fallback: true
   }
}

export const getStaticProps = async ({ params }) => {

	const portfolioItem = await getPortfolioItem(params.slug)
	return {
		props: {
			portfolioItem: portfolioItem.portfolio
      }
   }
}

export default function Home({ portfolioItem }) {
   const router = useRouter();
   //console.log(portfolioItem);

   if(router.isFallback){
      return <div>Loading</div>
   }

	return (
		<div className=''>
			<Head>
				<title>Personal Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className='space-y-10'>
				<div>
               <h1>{portfolioItem.title}</h1>
            </div>
			</div>

			
		</div>
	)
}
