import Head from 'next/head';
import Image from 'next/image';
import { getPortfolioSlugs, getPortfolioItem } from '../../utils/data';
import ReactMarkdown from 'react-markdown';

export const getStaticPaths = async () => {
   const slugsRes = await getPortfolioSlugs();
	const slugs = slugsRes.portfolios;

   return {
      paths: slugs.map(slug => ({params: {slug: slug.slug}})),
      fallback: false
   }
}

export const getStaticProps = async ({ params }) => {
	const portfolioItem = await getPortfolioItem(params.slug)
	return {
		props: {
			portfolioItem: portfolioItem.portfolio
      }
   }
}

export default function Home({ portfolioItem }) {

	console.log(portfolioItem);

	return (
		<div className=''>
			<Head>
				<title>{portfolioItem.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className='space-y-10'>
				<div>
               <h1>{portfolioItem.title}</h1>
					<p>{new Date(portfolioItem.date).toDateString()}</p>
					<p>{portfolioItem.description}</p>
					<Image 
						src={portfolioItem.coverImage.url}
						width={portfolioItem.coverImage.width}
						height={portfolioItem.coverImage.height}
					/>
					<div>
						{
							portfolioItem.tags.map(tag => (
								<span key={tag}>{tag}</span>
							))
						}
					</div>
					<section className='prose'>
						<ReactMarkdown>
							{portfolioItem.content.markdown}
						</ReactMarkdown>
					</section>
            </div>
			</div>

			
		</div>
	)
}
