import Head from 'next/head';
import Image from 'next/image';
import { getPortfolioSlugs, getPortfolioItem } from '../../utils/data';
import ReactMarkdown from 'react-markdown';

export const getStaticPaths = async () => {
   const slugsRes = await getPortfolioSlugs();
	const slugs = slugsRes.portfolios;

   return {
      paths: slugs.map(slug => ({params: {slug: slug.slug}})),
      fallback: false
   }
}

export const getStaticProps = async ({ params }) => {
	const portfolioItem = await getPortfolioItem(params.slug)
	return {
		props: {
			portfolioItem: portfolioItem.portfolio
      }
   }
}

export default function Home({ portfolioItem }) {

	return (
		<div className=''>
			<Head>
				<title>{portfolioItem.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className='space-y-10 max-w-3xl mx-auto px-6 sm:px-6 lg:px-0'>
				<div>
               <h1 className='text-center md:text-left text-4xl md:text-6xl  text-gray-900 font-bold'>{portfolioItem.title}</h1>
					<div className='flex flex-col md:flex-row justify-between items-center mb-10 mt-2'>
						<p className='text-gray-800 text-sm md:text-base'>{new Date(portfolioItem.date).toDateString()}</p>
						<div className=' flex justify-center items-center space-x-3'>
							{
								portfolioItem.tags.map(tag => (
									<span className='uppercase mt-5 text-xs md:text-sm md:tracking-wide md:m-2 p-2  md:px-2 md:py-1 bg-gray-100 text-gray-900 rounded-lg' key={tag}>{tag}</span>
								))
							}
						</div>
					</div>
					<p className='text-gray-700 text-justify mb-10'>{portfolioItem.description}</p>
					<div className='shadow-md'>
						<Image 
							src={portfolioItem.coverImage.url}
							width={portfolioItem.coverImage.width}
							height={portfolioItem.coverImage.height}
							objectFit='cover'
							layout='responsive'
							className='coverImage'
							alt={portfolioItem.title}
						/>
					</div>
					<section className='prose max-w-3xl mx-auto mt-10'>
						<ReactMarkdown>
							{portfolioItem.content.markdown}
						</ReactMarkdown>
					</section>
            </div>
			</div>

			
		</div>
	)
}
