import React from 'react';
import { getPosts } from '../../utils/data';
import Link from 'next/link';
import Head from 'next/head';

export const getStaticProps = async () => {
   const data = await getPosts();

   return {
      props: {
         posts: data.posts
      }
   }
}

const index = ({ posts }) => {
   return (
      <>
         <Head>
            <title>Blog</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className='max-w-3xl mx-auto px-6 sm:px-6 lg:px-0'>
            <div className='md:mt-20'>
               <div className='mb-5'>
                  <h1 className='text-3xl font-semibold text-center md:text-left'>All Posts</h1>
               </div>
               {
                  posts.map(post => (
                     <div className='grid grid-cols-1 md:grid-cols-4 py-6' key={post.slug}>
                        <div className='mb-2 md:mb-0 md:col-span-1'>
                           <p className='text-gray-500 text-sm'>{new Date(post.date).toDateString()}</p>
                        </div>

                        <div className='md:col-span-3'>
                           <Link href={`/blog/${post.slug}`}>
                              <a className='text-2xl font-semibold text-gray-900 hover:text-gray-500 transition-colors duration-300'>{post.title}</a>
                           </Link>
                           <p className='text-gray-700 leading-loose'>{post.description}</p>
                           <div className='text-sm text-gray-900 font-semibold mt-1'>
                              {post.author.name}
                           </div>
                        </div>
                     </div>
                  ))
               }
            </div>
         </div>
      </>
   )
}

export default index

