import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { getPostsAndPortfolios } from '../utils/data';
import Hero from '../components/Hero';


export const getStaticProps = async () => {

	const data = await getPostsAndPortfolios();
	return {
		props: {
			data
		}
	}
}

export default function Home({ data }) {

	return (
		<div className=''>
			<Head>
				<title>Pixel Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Hero/>

			<div className='space-y-10'>
				<div className='max-w-2xl mx-auto px-4 sm:px-6 lg:px-0'>
					{
						data?.portfolios.map(portfolio => (
							<div key={portfolio.slug}>
								<Link href={`/portfolio/${portfolio.slug}`}>
									<a>
										<div className='relative mb-10 image overflow-hidden rounded-lg transform transition-all duration-300 md:hover:scale-105'>
											<div className='absolute w-full h-full z-10 opacity-80 bg-green-900 '>
												<div className='absolute w-full h-full z-10 flex justify-center items-center flex-col text-center px-4 md:px-10'>
													<h3 className='text-white font-semibold text-xl md:text-3xl p-2 md:p-5 leading-relaxed'>
														{portfolio.title}
													</h3>
													<p className='text-gray-50 text-sm md:text-lg md:mt-4 line-clamp-2 md:line-clamp-none'>{portfolio.description}</p>
													<div className='mt-3 md:mt-10'>
														{portfolio.tags.map(tag => (
															<span className='text-white md:uppercase text-sm md:tracking-wide m-1 md:m-2 bg-green-500 px-2 py-1 rounded-lg font-bold' key={tag}>{tag}</span>
														))}
													</div>
												</div>
											</div>
											<Image
												src={portfolio.coverImage.url}
												width={portfolio.coverImage.width}
												height={portfolio.coverImage.height}
												objectFit='cover'
												className='absolute'
												layout='responsive'
												alt={portfolio.title}
											/>
										</div>
									</a>
								</Link>
							</div>
						))
					}
				</div>
	
				<div className='max-w-3xl mx-auto px-6 sm:px-6 lg:px-0'>
					<div className='md:mt-20'>
						<div className='mb-5'>
							<h1 className='text-3xl font-semibold text-center md:text-left'>Recent Posts</h1>
						</div>
						{
							data?.posts.map(post => (
								<div className='grid grid-cols-1 md:grid-cols-4 py-6' key={post.slug}>
									<div className='mb-2 md:mb-0 md:col-span-1'>
										<p className='text-gray-500 text-sm'>{new Date(post.date).toDateString()}</p>
									</div>

									<div className='md:col-span-3'>
										<Link href={`/blog/${post.slug}`}>
											<a className='text-2xl font-semibold text-gray-900 hover:text-gray-500 transition-colors duration-300'>{post.title}</a>
										</Link>
										<p className='text-gray-700 leading-loose'>{post.description}</p>
										<div className='text-sm text-gray-900 font-semibold mt-1'>
											{post.author.name}
										</div>
									</div>
								</div>
							))
						}
					</div>
				</div>
			</div>

			
		</div>
	)
}
