import Head from 'next/head';
import Link from 'next/link';
import { getPostsAndPortfolios } from '../utils/data';

export const getStaticProps = async () => {

	const data = await getPostsAndPortfolios();
	return {
		props: {
			data
		}
	}
}

export default function Home({ data }) {

	return (
		<div className=''>
			<Head>
				<title>Personal Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className='space-y-10'>
				<div>
					{
						data?.portfolios.map(portfolio => (
							<div key={portfolio.slug}>
								<Link href={`/portfolio/${portfolio.slug}`}>{portfolio.title}</Link>
							</div>
						))
					}
				</div>
	
				<div>
					{
						data?.posts.map(post => (
							<div key={post.slug}>
								<Link href={`/post/${post.slug}`}>{post.title}</Link>
							</div>
						))
					}
				</div>
			</div>

			
		</div>
	)
}
